name: release
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]-*'

jobs:
  pack_and_push:
    name: "release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        dotnet: ['5.0.202']
        include:
          - os: ubuntu-18.04
            RID: linux-x64
          #- os: windows-latest
          #  RID: win-x64
          - os: macos-latest
            RID: osx-x64
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: publish (server)
        shell: bash
        run: |
          dotnet publish -c Release \
          -o publish \
          -p:PublishReadyToRun=true \
          -p:PublishSingleFile=true \
          -p:PublishTrimmed=true \
          -p:RuntimeIdentifier=${{ matrix.RID }} \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained true \
          NLoop.Server \
          --version-suffix date$(date +%Y%m%d-%H%M).git-$(git rev-parse --short=7 HEAD)-${{ matrix.RID }}
      - name: publish (cli)
        shell: bash
        run: |
          dotnet publish -c Release \
          -o publish \
          -p:PublishReadyToRun=true \
          -p:PublishSingleFile=true \
          -p:PublishTrimmed=true \
          -p:RuntimeIdentifier=${{ matrix.RID }} \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          --self-contained true \
          NLoop.CLI \
          --version-suffix date$(date +%Y%m%d-%H%M).git-$(git rev-parse --short=7 HEAD)-${{ matrix.RID }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/nloopd
            publish/nloop-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
